func: rewrite a loop to appease -Wunreachable-code-loop-increment
This warning catches loops that can only execute once. It's unhappy
about the following code:

```
build/kati/func.cc:286:3: error: loop will run at most once (loop
increment never executed) [-Werror,-Wunreachable-code-loop-increment]
  for (StringPiece tok : WordScanner(text)) {
  ^~~
```

Since that behavior seems intended here, just tweak the code to silence
the warning.

b/150166387

Test: TreeHugger passed at
https://android-review.googlesource.com/c/platform/build/kati/+/1252837