fix implicit_pattern_rule_phony.mk
is this .PHONY support correct?

still failing in goma client build.
$(call do_cmd,cxx,1) isn't expanded correctly?
- missing -I flags?

  CXX(host) out/Debug/obj.target/protobuf_lite32/third_party/protobuf/protobuf/s
rc/google/protobuf/unknown_field_set.o
./third_party/protobuf/protobuf/src/google/protobuf/unknown_field_set.cc:42:10:
fatal error: 'google/protobuf/stubs/stl_util.h' file not found